In [4]:
import numpy as np
np.random.seed(0)
print(np.random.rand(3))
weights = np.random.randn(3, 4)
biases = np.random.randn(3)
print(weights)
print(biases)

[0.5488135  0.71518937 0.60276338]
[[-2.2683282   1.33354538 -0.84272405  1.96992445]
 [ 1.26611853 -0.50587654  2.54520078  1.08081191]
 [ 0.48431215  0.57914048 -0.18158257  1.41020463]]
[-0.37447169  0.27519832 -0.96075461]


In [3]:
import numpy as np
np.random.seed(0)
print(np.random.rand(3))
weights = np.random.randn(3, 4)
biases = np.random.randn(3)
print(weights)
print(biases)

[0.5488135  0.71518937 0.60276338]
[[-2.2683282   1.33354538 -0.84272405  1.96992445]
 [ 1.26611853 -0.50587654  2.54520078  1.08081191]
 [ 0.48431215  0.57914048 -0.18158257  1.41020463]]
[-0.37447169  0.27519832 -0.96075461]
